version: "3.7"
services:
  db:
    container_name: mysql8
    image: mysql:8
    environment:
      - MYSQL_DATABASE=ginapp
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3308:3306"
    networks:
      - ginapp
    restart: unless-stopped
  ginapp:
    container_name: ginapp
    image: ginapp:4
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ginapp
    restart: unless-stopped    
networks:
  ginapp:
    driver: bridge